CC = g++
CFLAGS = -Wall

main: main.o DB.o Parser.o
	$(CC) $(CFLAGS) -o main main.o DB.o Parser.o

main.o: main.cpp DB.h Solver.h
	$(CC) $(CFLAGS) -c main.cpp

DB.o: DB.cpp DB.h Parser.h
	$(CC) $(CFLAGS) -c DB.cpp

Parcer.o: Parser.cpp Parser.h
	$(CC) $(CFLAGS) -c Parser.cpp

clean:
	rm -f *.o main